/**
 * Tools Module
 *
 * MCP tool definitions and handlers for my core.
 */

export {
  identityTools,
  createIdentityGetAllHandler,
  createIdentityWriteHandler,
  createIdentityAppendHandler,
  createIdentityPrependHandler,
  createIdentityUpdateSectionHandler,
  createIdentityRewriteSectionHandler,
  createIdentityDeleteCustomHandler,
  createIdentityGetMetaHandler,
  createIdentitySetMetaHandler,
  IdentityGetAllSchema,
  IdentityWriteSchema,
  IdentityAppendSchema,
  IdentityPrependSchema,
  IdentityUpdateSectionSchema,
  IdentityRewriteSectionSchema,
  IdentityDeleteCustomSchema,
  IdentityGetMetaSchema,
  IdentitySetMetaSchema,
  type IdentityGetAllOutput,
  type IdentityOperationOutput,
  type IdentityWriteOutput,
} from "./identity.ts";

export {
  memoryTools,
  createMemoryCreateHandler,
  createMemorySearchHandler,
  createMemoryListHandler,
  createMemoryReadHandler,
  createMemoryUpdateHandler,
  createMemoryDeleteHandler,
  MemoryCreateSchema,
  MemorySearchSchema,
  MemoryListSchema,
  MemoryReadSchema,
  MemoryUpdateSchema,
  MemoryDeleteSchema,
  type MemoryCreateOutput,
  type MemorySearchOutput,
  type MemoryListOutput,
  type MemoryReadOutput,
  type MemoryUpdateOutput,
} from "./memory.ts";

export {
  syncTools,
  createSyncPullHandler,
  createSyncPushHandler,
  createSyncStatusHandler,
  SyncPullSchema,
  SyncPushSchema,
} from "./sync.ts";

export {
  snapshotTools,
  createSnapshotCreateHandler,
  createSnapshotListHandler,
  createSnapshotRestoreHandler,
  createSnapshotGetHandler,
  SnapshotCreateSchema,
  SnapshotListSchema,
  SnapshotGetSchema,
  SnapshotRestoreSchema,
  type SnapshotCreateOutput,
  type SnapshotListOutput,
  type SnapshotGetOutput,
  type SnapshotRestoreOutput,
} from "./snapshot.ts";

export {
  memoryConsolidateDescription,
  MemoryConsolidateSchema,
  createMemoryConsolidateHandler,
} from "./consolidation.ts";

export {
  graphTools,
  createGraphNodeCreateHandler,
  createGraphNodeGetHandler,
  createGraphNodeUpdateHandler,
  createGraphNodeDeleteHandler,
  createGraphNodeSearchHandler,
  createGraphNodeListHandler,
  createGraphEdgeCreateHandler,
  createGraphEdgeGetHandler,
  createGraphEdgeUpdateHandler,
  createGraphEdgeDeleteHandler,
  createGraphTraverseHandler,
  createGraphSubgraphHandler,
  createGraphInsightsHandler,
  createGraphStatsHandler,
  createGraphWriteTransactionHandler,
  GraphNodeCreateSchema,
  GraphNodeGetSchema,
  GraphNodeUpdateSchema,
  GraphNodeDeleteSchema,
  GraphNodeSearchSchema,
  GraphNodeListSchema,
  GraphEdgeCreateSchema,
  GraphEdgeGetSchema,
  GraphEdgeUpdateSchema,
  GraphEdgeDeleteSchema,
  GraphTraverseSchema,
  GraphSubgraphSchema,
  GraphInsightsSchema,
  GraphStatsSchema,
  GraphWriteTransactionSchema,
  type GraphNodeCreateOutput,
  type GraphNodeGetOutput,
  type GraphNodeUpdateOutput,
  type GraphNodeDeleteOutput,
  type GraphNodeSearchOutput,
  type GraphNodeListOutput,
  type GraphEdgeCreateOutput,
  type GraphEdgeGetOutput,
  type GraphEdgeUpdateOutput,
  type GraphEdgeDeleteOutput,
  type GraphTraverseOutput,
  type GraphSubgraphOutput,
  type GraphInsightsOutput,
  type GraphStatsOutput,
  type GraphWriteTransactionOutput,
} from "./graph.ts";
