/**
 * Tools Module
 *
 * MCP tool definitions and handlers for my core.
 */

export {
  identityTools,
  createIdentityGetAllHandler,
  createIdentityWriteHandler,
  createIdentityAppendHandler,
  createIdentityPrependHandler,
  createIdentityUpdateSectionHandler,
  createIdentityDeleteCustomHandler,
  IdentityGetAllSchema,
  IdentityWriteSchema,
  IdentityAppendSchema,
  IdentityPrependSchema,
  IdentityUpdateSectionSchema,
  IdentityDeleteCustomSchema,
  type IdentityGetAllOutput,
  type IdentityOperationOutput,
  type IdentityWriteOutput,
} from "./identity.ts";

export {
  memoryTools,
  createMemoryCreateHandler,
  createMemorySearchHandler,
  createMemoryListHandler,
  MemoryCreateSchema,
  MemorySearchSchema,
  MemoryListSchema,
  type MemoryCreateOutput,
  type MemorySearchOutput,
  type MemoryListOutput,
} from "./memory.ts";

export {
  syncTools,
  createSyncPullHandler,
  createSyncPushHandler,
  createSyncStatusHandler,
  SyncPullSchema,
  SyncPushSchema,
} from "./sync.ts";

export {
  snapshotTools,
  createSnapshotCreateHandler,
  createSnapshotListHandler,
  createSnapshotRestoreHandler,
  createSnapshotGetHandler,
  SnapshotCreateSchema,
  SnapshotListSchema,
  SnapshotGetSchema,
  SnapshotRestoreSchema,
  type SnapshotCreateOutput,
  type SnapshotListOutput,
  type SnapshotGetOutput,
  type SnapshotRestoreOutput,
} from "./snapshot.ts";

export {
  graphTools,
  createGraphNodeCreateHandler,
  createGraphNodeGetHandler,
  createGraphNodeUpdateHandler,
  createGraphNodeDeleteHandler,
  createGraphNodeSearchHandler,
  createGraphNodeListHandler,
  createGraphEdgeCreateHandler,
  createGraphEdgeGetHandler,
  createGraphEdgeUpdateHandler,
  createGraphEdgeDeleteHandler,
  createGraphTraverseHandler,
  createGraphSubgraphHandler,
  createGraphConnectMemoryHandler,
  createGraphGetMemoryNodesHandler,
  createGraphInsightsHandler,
  createGraphStatsHandler,
  createGraphWriteTransactionHandler,
  createGraphExtractFromMemoryHandler,
  GraphNodeCreateSchema,
  GraphNodeGetSchema,
  GraphNodeUpdateSchema,
  GraphNodeDeleteSchema,
  GraphNodeSearchSchema,
  GraphNodeListSchema,
  GraphEdgeCreateSchema,
  GraphEdgeGetSchema,
  GraphEdgeUpdateSchema,
  GraphEdgeDeleteSchema,
  GraphTraverseSchema,
  GraphSubgraphSchema,
  GraphConnectMemorySchema,
  GraphGetMemoryNodesSchema,
  GraphInsightsSchema,
  GraphStatsSchema,
  GraphWriteTransactionSchema,
  GraphExtractFromMemorySchema,
  type GraphNodeCreateOutput,
  type GraphNodeGetOutput,
  type GraphNodeUpdateOutput,
  type GraphNodeDeleteOutput,
  type GraphNodeSearchOutput,
  type GraphNodeListOutput,
  type GraphEdgeCreateOutput,
  type GraphEdgeGetOutput,
  type GraphEdgeUpdateOutput,
  type GraphEdgeDeleteOutput,
  type GraphTraverseOutput,
  type GraphSubgraphOutput,
  type GraphConnectMemoryOutput,
  type GraphGetMemoryNodesOutput,
  type GraphInsightsOutput,
  type GraphStatsOutput,
  type GraphWriteTransactionOutput,
  type GraphExtractFromMemoryOutput,
} from "./graph.ts";
